In [142]:
import solubility_library as sol
from imp import reload
reload(sol)
import numpy as np

In [143]:
c = solubility_library.Core_MgSi()

In [171]:
wt0 = np.array([1,2,3,4])
M = c.wt2M(wt0)
M_tot = np.sum(M)
X = c.M2X(M)
wt = c.M2wt(M)
wtp = c.M2wtp(M)
print(c.species)
print(M, np.sum(M))
print(X, np.sum(X))
print(wt, np.sum(wt))
print(wtp, np.sum(wtp))

['Mg', 'Si', 'O', 'Fe']
[ 0.0411438   0.07121112  0.18750703  0.07162682] 0.371488776509
[ 0.11075381  0.19169118  0.50474481  0.1928102 ] 1.0
[ 1.  2.  3.  4.] 10.0
[ 0.1  0.2  0.3  0.4] 1.0


In [172]:
M_tot = np.sum(M)
M = c.X2M(X, M_tot=M_tot)
wt = c.X2wt(X, M_tot=M_tot)
wt_tot = np.sum(wt)
wtp = c.X2wtp(X)
print(c.species)
print(M, np.sum(M))
print(X, np.sum(X))
print(wt, np.sum(wt))
print(wtp, np.sum(wtp))

['Mg', 'Si', 'O', 'Fe']
[ 0.0411438   0.07121112  0.18750703  0.07162682] 0.371488776509
[ 0.11075381  0.19169118  0.50474481  0.1928102 ] 1.0
[ 1.  2.  3.  4.] 10.0
[ 0.1  0.2  0.3  0.4] 1.0


In [173]:
M_tot = np.sum(M)
M = c.X2M(X, wt_tot=wt_tot)
wt = c.X2wt(X, wt_tot=wt_tot)
wtp = c.X2wtp(X)
print(c.species)
print(M, np.sum(M))
print(X, np.sum(X))
print(wt, np.sum(wt))
print(wtp, np.sum(wtp))

['Mg', 'Si', 'O', 'Fe']
[ 0.0411438   0.07121112  0.18750703  0.07162682] 0.371488776509
[ 0.11075381  0.19169118  0.50474481  0.1928102 ] 1.0
[ 1.  2.  3.  4.] 10.0
[ 0.1  0.2  0.3  0.4] 1.0


In [174]:
M = c.wt2M(wt)
X = c.wt2X(wt)
wtp = c.wt2wtp(wt)
print(c.species)
print(M, np.sum(M))
print(X, np.sum(X))
print(wt, np.sum(wt))
print(wtp, np.sum(wtp))

['Mg', 'Si', 'O', 'Fe']
[ 0.0411438   0.07121112  0.18750703  0.07162682] 0.371488776509
[ 0.11075381  0.19169118  0.50474481  0.1928102 ] 1.0
[ 1.  2.  3.  4.] 10.0
[ 0.1  0.2  0.3  0.4] 1.0


In [175]:
wt_tot = np.sum(wt)
M = c.wtp2M(wtp, wt_tot=wt_tot)
X = c.wtp2X(wtp)
wt = c.wtp2wt(wtp, wt_tot=wt_tot)
print(c.species)
print(M, np.sum(M))
print(X, np.sum(X))
print(wt, np.sum(wt))
print(wtp, np.sum(wtp))

['Mg', 'Si', 'O', 'Fe']
[ 0.0411438   0.07121112  0.18750703  0.07162682] 0.371488776509
[ 0.11075381  0.19169118  0.50474481  0.1928102 ] 1.0
[ 1.  2.  3.  4.] 10.0
[ 0.1  0.2  0.3  0.4] 1.0


In [176]:
wt_tot = np.sum(wt)
M = c.wtp2M(wtp, M_tot=M_tot)
X = c.wtp2X(wtp)
wt = c.wtp2wt(wtp, M_tot=M_tot)
print(c.species)
print(M, np.sum(M))
print(X, np.sum(X))
print(wt, np.sum(wt))
print(wtp, np.sum(wtp))

['Mg', 'Si', 'O', 'Fe']
[ 0.0411438   0.07121112  0.18750703  0.07162682] 0.371488776509
[ 0.11075381  0.19169118  0.50474481  0.1928102 ] 1.0
[ 1.  2.  3.  4.] 10.0
[ 0.1  0.2  0.3  0.4] 1.0


# Mantle

In [77]:
m = solubility_library.Mantle_MgSi()

In [78]:
# wt0 = np.array([1,1,1,1,1])
# M = m.wt2M(wt0)
M = np.array([1,1,1,1,1])
X = m.M2X(M)
wt = m.M2wt(M)
wtp = m.M2wtp(M)
print(m.species)
print(M, np.sum(M))
print(X, np.sum(X))
print(wt, np.sum(wt))
print(wtp, np.sum(wtp))

['MgO', 'FeO', 'SiO2', 'MgSiO3', 'FeSiO3']
[1 1 1 1 1] 5
[ 0.2  0.2  0.2  0.2  0.2] 1.0
[  40.3044   71.8444   60.0843  100.3887  131.9287] 404.5505
[ 0.09962761  0.17759068  0.14852114  0.24814875  0.32611182] 1.0


In [79]:
M_tot = np.sum(M)
M = m.X2M(X,M_tot)
wt = m.X2wt(X,M_tot)
wtp = m.X2wtp(X,M_tot)
print(m.species)
print(M, np.sum(M))
print(X, np.sum(X))
print(wt, np.sum(wt))
print(wtp, np.sum(wtp))

['MgO', 'FeO', 'SiO2', 'MgSiO3', 'FeSiO3']
[ 1.  1.  1.  1.  1.] 5.0
[ 0.2  0.2  0.2  0.2  0.2] 1.0
[  40.3044   71.8444   60.0843  100.3887  131.9287] 404.5505
[ 0.09962761  0.17759068  0.14852114  0.24814875  0.32611182] 1.0


In [80]:
M = m.wt2M(wt)
X = m.wt2X(wt)
wtp = m.wt2wtp(wt)
print(m.species)
print(M, np.sum(M))
print(X, np.sum(X))
print(wt, np.sum(wt))
print(wtp, np.sum(wtp))

['MgO', 'FeO', 'SiO2', 'MgSiO3', 'FeSiO3']
[ 1.  1.  1.  1.  1.] 5.0
[ 0.2  0.2  0.2  0.2  0.2] 1.0
[  40.3044   71.8444   60.0843  100.3887  131.9287] 404.5505
[ 0.09962761  0.17759068  0.14852114  0.24814875  0.32611182] 1.0


In [81]:
wt_tot = np.sum(wt)
M = m.wtp2M(wtp, wt_tot)
X = m.wtp2X(wtp, wt_tot)
wt = m.wtp2wt(wtp, wt_tot)
print(m.species)
print(M, np.sum(M))
print(X, np.sum(X))
print(wt, np.sum(wt))
print(wtp, np.sum(wtp))

['MgO', 'FeO', 'SiO2', 'MgSiO3', 'FeSiO3']
[ 1.  1.  1.  1.  1.] 5.0
[ 0.2  0.2  0.2  0.2  0.2] 1.0
[  40.3044   71.8444   60.0843  100.3887  131.9287] 404.5505
[ 0.09962761  0.17759068  0.14852114  0.24814875  0.32611182] 1.0
